spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: provider
mybatis:
  config-location: classpath:config/mybatiscfg.xml
  type-aliases-package: cn.fuyong.springcloud.entity.dev
  mapper-locations: classpath:mapper/**/*.xml
---
spring:
  profiles: test
mybatis:
  config-location: classpath:config/mybatiscfg.xml
  type-aliases-package: cn.fuyong.springcloud.entity.test
  mapper-locations: classpath:mapper/**/*.xml
