spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
    application:
      name: micservicecloud-config-dev
---
spring:
  profiles: test
    application:
      name: micservicecloud-config-test
